export const GET_BOUNTY_PROGRAMS_REQUEST = "GET_BOUNTY_PROGRAMS_REQUEST";
export const GET_BOUNTY_PROGRAMS_SUCCESS = "GET_BOUNTY_PROGRAMS_SUCCESS";
export const GET_BOUNTY_PROGRAMS_FAIL = "GET_BOUNTY_PROGRAMS_FAIL";


export const CREATE_BOUNTY_PROGRAM_REQUEST = "CREATE_BOUNTY_PROGRAM_REQUEST";
export const CREATE_BOUNTY_PROGRAM_SUCCESS = "CREATE_BOUNTY_PROGRAM_SUCCESS";
export const CREATE_BOUNTY_PROGRAM_FAIL = "CREATE_BOUNTY_PROGRAM_FAIL";


export const UPDATE_BOUNTY_PROGRAM_REQUEST = "UPDATE_BOUNTY_PROGRAM_REQUEST";
export const UPDATE_BOUNTY_PROGRAM_SUCCESS = "UPDATE_BOUNTY_PROGRAM_SUCCESS";
export const UPDATE_BOUNTY_PROGRAM_FAIL = "UPDATE_BOUNTY_PROGRAM_FAIL";


export const DELETE_BOUNTY_PROGRAM_REQUEST = "DELETE_BOUNTY_PROGRAM_REQUEST";
export const DELETE_BOUNTY_PROGRAM_SUCCESS = "DELETE_BOUNTY_PROGRAM_SUCCESS";
export const DELETE_BOUNTY_PROGRAM_FAIL = "DELETE_BOUNTY_PROGRAM_FAIL";

export const CLEAR_BOUNTY_PROGRAMS = "CLEAR_BOUNTY_PROGRAMS";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";