//bug reports
export const GET_BUG_REPORTS_REQUEST = "GET_BUG_REPORTS_REQUEST";
export const GET_BUG_REPORTS_SUCCESS = "GET_BUG_REPORTS_SUCCESS";
export const GET_BUG_REPORTS_FAIL = "GET_BUG_REPORTS_FAIL";


export const CREATE_BUG_REPORT_REQUEST = "CREATE_BUG_REPORT_REQUEST";
export const CREATE_BUG_REPORT_SUCCESS = "CREATE_BUG_REPORT_SUCCESS";
export const CREATE_BUG_REPORT_FAIL = "CREATE_BUG_REPORT_FAIL";

export const ACCEPT_BUG_REPORT_REQUEST = "ACCEPT_BUG_REPORT_REQUEST";
export const ACCEPT_BUG_REPORT_SUCCESS = "ACCEPT_BUG_REPORT_SUCCESS";
export const ACCEPT_BUG_REPORT_FAIL = "ACCEPT_BUG_REPORT_FAIL";

export const REJECT_BUG_REPORT_REQUEST = "REJECT_BUG_REPORT_REQUEST";
export const REJECT_BUG_REPORT_SUCCESS = "REJECT_BUG_REPORT_SUCCESS";
export const REJECT_BUG_REPORT_FAIL = "REJECT_BUG_REPORT_FAIL";

export const CLEAR_BUG_REPORTS = "CLEAR_BUG_REPORTS";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";